# Site Information
title: Yerim Kim
description: Undergraduate Student | Department of Computer Science | Sookmyung Women’s University

# Base URL and Custom URL
baseurl: /gradfolio # Repository name
url: "" # If you have a custom domain, specify it here (e.g., https://yourdomain.com)

# Contact Information
email: yerim205@sookmyung.ac.kr

# Profile Photo
profile_photo: profile.jpeg # Make sure the image is in the appropriate directory (e.g., assets/images/)

# Pagination Settings
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social Media Links
github: "#"
instagram: "#"

# Markdown Settings
highlighter: rouge
markdown: kramdown

# Analytics Tracker (Optional)
analytics:

# HTML Compression
compress_html:
  clippings:
    [
      html,
      div,
      p,
      ul,
      td,
      h1,
      h2,
      h3,
      h4,
      link,
      meta,
      footer,
      nav,
      img,
      header,
      hr,
      br,
      head,
      style,
      li,
      ul,
      ol,
      time,
      main,
      script,
      title,
    ]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collections Configuration
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

# SASS Settings
sass:
  sass_dir: /assets/css/_sass
  style: compressed

# Include/Exclude Files and Directories
include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
